name: fintap
description: A new Flutter project.
version: 1.0.3+5
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  animator: ^3.3.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^4.0.1
  country_pickers: ^2.0.0
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  get: ^4.6.5
  http: ^0.13.5
  im_stepper: ^1.0.1+1
  images_picker: ^1.2.11
  intl: ^0.18.0
  local_auth: ^2.1.6
  new_version_plus: ^0.0.9
  permission_handler: ^10.2.0
  pin_code_fields: ^7.3.0
  pull_to_refresh_flutter3: ^2.0.1
  qr_code_scanner: ^1.0.1
  share_plus: ^7.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  upgrader: ^7.1.0
  url_launcher: ^6.1.11
  webview_flutter: ^3.0.4
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/fintapicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
       
